Repository Arquisoft/dede_en2a, pull requests merged in 2022-02, with the labels that each got.

#19 Added Lorenzo's UO to Readme file
  README.md
Labels: documentation

#22 Added Requirements Overview section
  docs/01_introduction_and_goals.adoc
Labels: documentation

#24 Added the Conventions Table on Section 2.
  docs/02_architecture_constraints.adoc
Labels: documentation

#25 Added the quality goals to the first section
  docs/01_introduction_and_goals.adoc
Labels: documentation

#35 3.2 technical context
  docs/03_system_scope_and_context.adoc
Labels: documentation

#34 added organizational decisions + quality goals
  docs/04_solution_strategy.adoc
Labels: documentation

#40 Added Section 6. Runtime View.
  docs/06_runtime_view.adoc
Labels: documentation

#39 Added Section3.1 Business context
  docs/03_system_scope_and_context.adoc
Labels: documentation

#42 Sections Technology Stack and Dev Tools ri-added because of conflicts
  docs/04_solution_strategy.adoc
Labels: documentation

#41 Added the design decision we have so far
  docs/04_solution_strategy.adoc
  docs/09_design_decisions.adoc
Labels: documentation

#57 Quality goals and design decisions revisited
  docs/01_introduction_and_goals.adoc
  docs/09_design_decisions.adoc
Labels: bug 🐛, review ✅

#66 Merge first prototype working
  .gitignore
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/09_design_decisions.adoc
  docs/images/level1.jpg
  docs/images/level2.jpg
  docs/images/level3.jpg
  restapi/api.ts
  restapi/models/users.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/products/Product.ts
  restapi/products/ProductController.ts
  restapi/products/ProductRoutes.ts
  restapi/products/product.http
  restapi/server.ts
  restapi/tests/api.test.ts
  restapi/users/User.ts
  restapi/users/UserController.ts
  restapi/users/UserRoutes.ts
  restapi/users/user.http
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Pay.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductList.tsx
  webapp/src/components/Shopping.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/images/1234.jpg
  webapp/src/images/1236.jpg
  webapp/src/images/1237.jpg
  webapp/src/images/1347.jpg
  webapp/src/shared/shareddtypes.ts
Labels: database 📦, application logic 📐, i made something 😇

#68 Section 5 updated
  docs/05_building_block_view.adoc
  docs/images/level1.jpg
  docs/images/level1.png
  docs/images/level2.jpg
  docs/images/level2.png
  docs/images/level3.jpg
  docs/images/level3.png
Labels: documentation 📖, delivery contribution ✉️

#70 Stakeholder review
  docs/01_introduction_and_goals.adoc
Labels: bug 🐛, documentation 📖, review ✅

#71 Database schemas
  .gitignore
  restapi/carts/Cart.ts
  restapi/carts/CartController.ts
  restapi/carts/CartRoutes.ts
  restapi/orders/Order.ts
  restapi/orders/OrderController.ts
  restapi/orders/OrderProduct.ts
  restapi/orders/OrderRoutes.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/users/User.ts
  restapi/users/UserController.ts
  restapi/users/user.http
Labels: database 📦, backend 🐱‍👤

#72 Updating the looks and user management
  docs/package-lock.json
  restapi/package-lock.json
  restapi/package.json
  webapp/package-lock.json
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Checkout.tsx
  webapp/src/components/Footer.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Pay.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductList.tsx
  webapp/src/components/Shopping.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/components/SignIn.tsx
  webapp/src/components/SignUp.tsx
  webapp/src/index.css
  webapp/src/shared/shareddtypes.ts
Labels: application logic 📐, frontend 👼

#73 Implementing the checkout part of the application
  webapp/src/components/Checkout.tsx
  webapp/src/components/Shopping.tsx
Labels: application logic 📐, backend 🐱‍👤

#76 Cart modification to prevent render error
  webapp/src/App.tsx
  webapp/src/components/Shopping.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/shared/shareddtypes.ts
Labels: application logic 📐, frontend 👼
