Repository Arquisoft/dede_en2a, pull requests merged in 2022-04, with the labels that each got.

#209 More back tests
  restapi/api.ts
  restapi/models/users.ts
  restapi/orders/OrderController.ts
  restapi/reviews/ReviewController.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
Labels: backend 🐱‍👤, test 🔧

#206 Pick UP locations :)
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.css
  webapp/src/api/api.ts
  webapp/src/components/CustomRadioGroup.tsx
  webapp/src/components/checkout/Checkout.tsx
  webapp/src/components/checkout/CheckoutStepper.tsx
  webapp/src/components/checkout/Review.tsx
  webapp/src/components/checkout/ShippingAddress.tsx
  webapp/src/components/checkout/ShippingCosts.tsx
  webapp/src/components/checkout/ShippingMethod.tsx
  webapp/src/components/checkout/address/StreetAddress.tsx
  webapp/src/components/checkout/address/WebIdForm.tsx
  webapp/src/components/checkout/shipping/PickUpLocationsMap.tsx
  webapp/src/components/checkout/shipping/ShippingMethodForm.tsx
  webapp/src/components/checkout/shipping/ShippingRouteMap.tsx
  webapp/src/components/register/SignUp.tsx
  webapp/src/helpers/ComputeDistanceHelper.ts
  webapp/src/helpers/ShippingMethodHelper.ts
  webapp/src/index.css
  webapp/src/tests/products/ProductBox.test.tsx
  webapp/src/tests/products/ProductList.test.tsx
  webapp/tsconfig.json
Labels: application logic 📐, frontend 👼

#211 Section 5
  docs/05_building_block_view.adoc
  docs/images/level3.png
Labels: documentation 📖

#218 Test product speed dialog
  webapp/src/components/products/ProductSpeedDial.tsx
  webapp/src/tests/products/ProductSpeedDial.test.tsx
Labels: test 🔧

#219 Test footer
  webapp/src/tests/Footer.test.tsx
Labels: test 🔧

#215 Section 7
  docs/07_deployment_view.adoc
Labels: documentation 📖

#216 Sections 9, 10 and 11 included in the documentation
  docs/01_introduction_and_goals.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
Labels: documentation 📖

#210 Email branch
  restapi/package-lock.json
  restapi/package.json
  restapi/pdf/6274e3bb-6d44-46a6-b53e-b041b9645a60.pdf
  restapi/utils/PDFHelper.ts
  restapi/utils/emailSender.ts
  webapp/src/App.tsx
Labels: bug 🐛, backend 🐱‍👤

#220 Improving the responsiveness of the app and trying to solve bugs
  webapp/src/components/FeaturedProducts.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/cart/ShoppingCart.tsx
  webapp/src/components/checkout/Checkout.tsx
  webapp/src/components/checkout/CheckoutStepper.tsx
  webapp/src/components/checkout/OrderConfirmation.tsx
  webapp/src/components/checkout/Review.tsx
  webapp/src/components/checkout/ShippingAddress.tsx
  webapp/src/components/checkout/ShippingMethod.tsx
  webapp/src/components/checkout/shipping/PickUpLocationsMap.tsx
  webapp/src/components/dashboard/orders/OrderList.tsx
  webapp/src/components/home/FeaturedProducts.tsx
  webapp/src/components/home/Hero.tsx
  webapp/src/components/products/ProductComment.tsx
  webapp/src/components/products/ProductCommentList.tsx
  webapp/src/components/products/ProductDetails.tsx
  webapp/src/helpers/ShippingMethodHelper.ts
Labels: bug 🐛, frontend 👼

#224 Section 8 and 3 updated
  docs/03_system_scope_and_context.adoc
  docs/08_concepts.adoc
Labels: documentation 📖

#237 Back end tests
  restapi/orders/Order.ts
  restapi/orders/OrderController.ts
  restapi/products/ProductController.ts
  restapi/reviews/ReviewController.ts
  restapi/tests/api.test.ts
  restapi/tests/orders.test.ts
  restapi/tests/products.test.ts
  restapi/tests/reviews.test.ts
  restapi/tests/users.test.ts
  restapi/users/UserController.ts
  restapi/utils/PDFHelper.ts
  restapi/utils/emailSender.ts
  restapi/utils/generateToken.ts
Labels: database 📦, backend 🐱‍👤, delivery contribution ✉️, test 🔧

#238 Product categories
  restapi/products/Product.ts
  restapi/products/ProductController.ts
  restapi/products/ProductRoutes.ts
  restapi/products/product.http
  restapi/tests/orders.test.ts
  restapi/tests/products.test.ts
  restapi/utils/PDFHelper.ts
  restapi/utils/emailSender.ts
  webapp/src/api/api.ts
  webapp/src/components/checkout/Checkout.tsx
  webapp/src/components/dashboard/products/DeleteProduct.tsx
  webapp/src/components/dashboard/products/UploadProduct.tsx
  webapp/src/helpers/ShoppingCartHelper.ts
  webapp/src/shared/shareddtypes.ts
  webapp/src/tests/cart/ShoppingCart.test.tsx
  webapp/src/tests/cart/ShoppingCartTable.test.tsx
  webapp/src/tests/products/ProductBox.test.tsx
  webapp/src/tests/products/ProductDetails.test.tsx
  webapp/src/tests/products/ProductList.test.tsx
Labels: bug 🐛, database 📦, application logic 📐, backend 🐱‍👤, frontend 👼, delivery contribution ✉️, task 👌, test 🔧

#239 Redirecting routes
  webapp/src/App.tsx
  webapp/src/components/RedirectHome.tsx
  webapp/src/components/checkout/Checkout.tsx
  webapp/src/components/dashboard/Dashboard.tsx
  webapp/src/components/dashboard/products/DeleteProduct.tsx
  webapp/src/components/dashboard/products/UploadProduct.tsx
  webapp/src/components/home/FeaturedProducts.tsx
  webapp/src/components/register/SignIn.tsx
  webapp/src/components/register/SignUp.tsx
  webapp/src/images/0052.png
  webapp/src/images/1237.png
Labels: application logic 📐, frontend 👼

#242 Map correct address
  webapp/src/components/checkout/shipping/PickUpLocationsMap.tsx
Labels: application logic 📐, frontend 👼

#244 Update section 7
  docs/07_deployment_view.adoc
Labels: documentation 📖

#245 Edit product
  restapi/public/53.png
  restapi/reviews/ReviewController.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/dashboard/products/ProductList.tsx
  webapp/src/components/dashboard/products/UploadProduct.tsx
  webapp/src/components/products/ReviewDialog.tsx
Labels: application logic 📐, frontend 👼

#247 Shop products filter
  webapp/src/components/Shop.tsx
Labels: frontend 👼

#251 Carrier service api
  carrier-service-api/package-lock.json
  carrier-service-api/package.json
  carrier-service-api/server.ts
  carrier-service-api/src/controllers/RatesController.ts
  carrier-service-api/src/models/Carrier.ts
  carrier-service-api/src/models/Rates.ts
  carrier-service-api/src/routes/RatesRoutes.ts
  carrier-service-api/tsconfig.json
  restapi/orders/OrderController.ts
  restapi/orders/OrderRoutes.ts
  restapi/products/Product.ts
  restapi/products/ProductController.ts
  restapi/products/product.http
  restapi/public/53.png
  restapi/reviews/Review.ts
  restapi/reviews/ReviewController.ts
  restapi/tests/orders.test.ts
  restapi/tests/products.test.ts
  restapi/tests/reviews.test.ts
  restapi/tests/users.test.ts
  restapi/users/UserController.ts
  restapi/utils/WebIDValidation.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/api/carriersApi.ts
  webapp/src/components/checkout/Checkout.tsx
  webapp/src/components/checkout/Review.tsx
  webapp/src/components/checkout/ShippingAddress.tsx
  webapp/src/components/checkout/ShippingMethod.tsx
  webapp/src/components/checkout/address/StreetAddress.tsx
  webapp/src/components/checkout/shipping/CarriersRatesForm.tsx
  webapp/src/components/checkout/shipping/PickUpLocationsMap.tsx
  webapp/src/components/checkout/shipping/ShippingMethodForm.tsx
  webapp/src/components/checkout/shipping/ShippingRouteMap.tsx
  webapp/src/components/dashboard/account/AccountDetails.tsx
  webapp/src/components/dashboard/products/DeleteProduct.tsx
  webapp/src/components/dashboard/products/UploadProduct.tsx
  webapp/src/helpers/ComputeDistanceHelper.ts
  webapp/src/helpers/ShippingMethodHelper.ts
  webapp/src/helpers/ShoppingCartHelper.ts
  webapp/src/helpers/SolidHelper.ts
  webapp/src/shared/shareddtypes.ts
  webapp/src/tests/cart/ShoppingCart.test.tsx
  webapp/src/tests/cart/ShoppingCartTable.test.tsx
  webapp/src/tests/products/ProductBox.test.tsx
  webapp/src/tests/products/ProductDetails.test.tsx
  webapp/src/tests/products/ProductList.test.tsx
Labels: application logic 📐, backend 🐱‍👤

#255 Adding download PDF and some minor issues solved
  restapi/orders/OrderController.ts
  restapi/server.ts
  restapi/tests/orders.test.ts
  restapi/tests/products.test.ts
  restapi/tests/reviews.test.ts
  restapi/tests/users.test.ts
  restapi/utils/InvoiceGenerator.ts
  restapi/utils/PDFHelper.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/cart/ShoppingCart.tsx
  webapp/src/components/checkout/Checkout.tsx
  webapp/src/components/checkout/DownloadButton.tsx
  webapp/src/components/checkout/OrderConfirmation.tsx
  webapp/src/components/products/ProductBox.tsx
  webapp/src/helpers/ImageHelper.ts
  webapp/src/helpers/ShoppingCartHelper.ts
Labels: bug 🐛, application logic 📐, backend 🐱‍👤, frontend 👼

#257 Home tests
  webapp/src/components/home/FeaturedProducts.tsx
  webapp/src/components/home/Hero.tsx
  webapp/src/tests/home/FeaturedProducts.test.tsx
  webapp/src/tests/home/Hero.test.tsx
  webapp/src/tests/home/Home.test.tsx
Labels: test 🔧

#261 New search system done!
  webapp/src/components/dashboard/products/DeleteProduct.tsx
  webapp/src/components/dashboard/products/UploadProduct.tsx
Labels: frontend 👼

#260 Review modification and update done!
  restapi/reviews/ReviewController.ts
  restapi/reviews/ReviewRoutes.ts
  webapp/src/api/api.ts
  webapp/src/components/products/ProductDetails.tsx
  webapp/src/components/products/ReviewDialog.tsx
Labels: backend 🐱‍👤, frontend 👼

#263 Checkout tests
  webapp/src/components/checkout/Review.tsx
  webapp/src/components/checkout/ShippingAddress.tsx
  webapp/src/components/checkout/ShippingMethod.tsx
  webapp/src/components/checkout/address/StreetAddress.tsx
  webapp/src/components/checkout/shipping/CarriersRatesForm.tsx
  webapp/src/components/checkout/shipping/ShippingMethodForm.tsx
  webapp/src/helpers/ComputeDistanceHelper.ts
  webapp/src/setupTests.ts
  webapp/src/tests/checkout/Checkout.test.tsx
  webapp/src/tests/checkout/Review.test.tsx
  webapp/src/tests/checkout/ShippingAddress.test.tsx
  webapp/src/tests/checkout/ShippingMethod.test.tsx
  webapp/src/tests/checkout/shipping/CarriersRatesForm.test.tsx
  webapp/src/tests/checkout/shipping/ShippingMethodForm.test.tsx
  webapp/src/tests/checkout/shipping/ShippingRouteMap.test.tsx
Labels: frontend 👼, test 🔧

#265 E2e tests
  webapp/e2e/features/get-products.feature
  webapp/e2e/features/get-reviews.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/get-products.ts
  webapp/e2e/steps/get-reviews.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/dashboard/orders/OrderDetails.tsx
  webapp/src/components/home/Hero.tsx
Labels: frontend 👼, review ✅, task 👌, decision 🧠
