Repository Arquisoft/dede_en2a, pull requests merged in 2022-03, with the labels that each got.

#77 Simple shipping costs calculation
  webapp/src/components/Checkout.tsx
  webapp/src/components/ShippingCosts.tsx
  webapp/src/util/distanceCalculation.ts
Labels: application logic 📐

#78 Fixing some of the issues we had in the first delivery
  docs/02_architecture_constraints.adoc
  docs/04_solution_strategy.adoc
  docs/09_design_decisions.adoc
Labels: documentation 📖, review ✅

#80 User, products and orders error manage on create request
  restapi/orders/OrderController.ts
  restapi/products/ProductController.ts
  restapi/users/UserController.ts
  restapi/users/user.http
Labels: database 📦

#81 Accessing the SOLID pod from a given webID
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/ShippingCosts.tsx
Labels: application logic 📐, frontend 👼

#79 Improving the checkout part of the application
  webapp/src/App.tsx
  webapp/src/components/Checkout.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/Review.tsx
  webapp/src/components/ShippingCosts.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/helpers/ShoppingCartHelper.ts
Labels: frontend 👼

#82 Cart stored in session
  webapp/src/App.tsx
Labels: application logic 📐

#83 Some bug fixing regarding stock management
  restapi/carts/Cart.ts
  webapp/src/App.tsx
  webapp/src/components/Checkout.tsx
  webapp/src/components/Footer.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductList.tsx
  webapp/src/components/Review.tsx
  webapp/src/components/ShippingCosts.tsx
  webapp/src/components/Shopping.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/helpers/ComputeDistanceHelper.ts
Labels: bug 🐛, application logic 📐, frontend 👼

#84 Fixing stock management at product list view
  webapp/src/App.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductList.tsx
Labels: application logic 📐

#86 Checkout message is now shown
  webapp/src/components/Checkout.tsx
Labels: frontend 👼

#85 Sign in branch
  restapi/package-lock.json
  restapi/package.json
  restapi/users/User.ts
  restapi/users/UserController.ts
  restapi/users/UserRoutes.ts
  restapi/users/user.http
  restapi/utils/generateToken.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/NavBar.tsx
  webapp/src/components/SignIn.tsx
  webapp/src/components/SignUp.tsx
Labels: application logic 📐, backend 🐱‍👤, frontend 👼

#88 Sign in and sign up validation
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/SignIn.tsx
  webapp/src/components/SignUp.tsx
  webapp/src/helpers/CheckFieldsHelper.ts
Labels: application logic 📐

#89 Pay Pal API integration
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.tsx
  webapp/src/components/Billing.tsx
  webapp/src/components/Checkout.tsx
  webapp/src/components/Review.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/helpers/ShoppingCartHelper.ts
Labels: application logic 📐, frontend 👼

#91 Product rating schema and routes
  restapi/reviews/Review.ts
  restapi/reviews/ReviewController.ts
  restapi/reviews/ReviewRoutes.ts
  restapi/server.ts
Labels: database 📦

#95 Adding user comments to products
  webapp/src/api/api.ts
  webapp/src/components/ProductComment.tsx
  webapp/src/components/ProductCommentList.tsx
  webapp/src/components/ProductDetails.tsx
  webapp/src/shared/shareddtypes.ts
Labels: database 📦, application logic 📐

#101 Order saving
  restapi/orders/Order.ts
  restapi/orders/OrderController.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Checkout.tsx
  webapp/src/components/OrderItem.tsx
  webapp/src/components/Orders.tsx
  webapp/src/helpers/ShoppingCartHelper.ts
  webapp/src/shared/shareddtypes.ts
Labels: application logic 📐

#94 User verification
  restapi/package-lock.json
  restapi/package.json
  restapi/users/User.ts
  restapi/users/UserController.ts
  restapi/users/UserRoutes.ts
  restapi/users/UserVerification.ts
  restapi/users/user.http
  restapi/views/notVerified.html
  restapi/views/styles.css
  restapi/views/verified.html
  webapp/src/api/api.ts
  webapp/src/components/SignIn.tsx
  webapp/src/components/SignUp.tsx
Labels: application logic 📐

#102 Updating requirements section
  docs/01_introduction_and_goals.adoc
Labels: documentation 📖

#107 Improving the order management including it in the user's dashboard
  docs/package-lock.json
  restapi/orders/Order.ts
  restapi/orders/OrderController.ts
  restapi/orders/OrderRoutes.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Checkout.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/OrderDetails.tsx
  webapp/src/components/OrderItem.tsx
  webapp/src/components/OrderList.tsx
  webapp/src/components/Orders.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductDetails.tsx
  webapp/src/components/Shopping.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/helpers/ShoppingCartHelper.ts
  webapp/src/shared/shareddtypes.ts
Labels: database 📦, application logic 📐, frontend 👼, i made something 😇

#110 ratingV2
  restapi/reviews/ReviewController.ts
  restapi/reviews/ReviewRoutes.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/NavBar.tsx
  webapp/src/components/ProductDetails.tsx
  webapp/src/components/ProductSpeedDial.tsx
  webapp/src/components/ReviewDialog.tsx
  webapp/src/components/ShareDialog.tsx
  webapp/src/components/ShoppingCart.tsx
Labels: backend 🐱‍👤, frontend 👼

#118 Bug fixing and loading feedback when calculating the shipping costs
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/decision.md
  .github/ISSUE_TEMPLATE/meeting-minutes-finished.md
  .github/ISSUE_TEMPLATE/task-for-the-kanban.md
  .github/ISSUE_TEMPLATE/work-done-for-the-delivery.md
  .github/PULL_REQUEST_TEMPLATE/basic_pull_request.md
  .github/pull_request_template.md
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/09_design_decisions.adoc
  docs/images/level1.jpg
  docs/images/level1.png
  docs/images/level2.jpg
  docs/images/level2.png
  docs/images/level3.jpg
  docs/images/level3.png
  restapi/server.ts
  webapp/src/App.tsx
  webapp/src/components/Checkout.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductComment.tsx
  webapp/src/components/ProductCommentList.tsx
  webapp/src/components/ProductDetails.tsx
  webapp/src/components/ProductList.tsx
  webapp/src/components/ShippingCosts.tsx
  webapp/src/components/Shopping.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/helpers/ShoppingCartHelper.ts
Labels: bug 🐛, i made something 😇

#117 Creating a tiny landing page
  webapp/src/App.tsx
  webapp/src/components/Billing.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/OrderDetails.tsx
  webapp/src/components/OrderList.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductComment.tsx
  webapp/src/components/ProductCommentList.tsx
  webapp/src/components/ProductDetails.tsx
  webapp/src/components/ProductList.tsx
  webapp/src/components/Shop.tsx
  webapp/src/components/Shopping.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/components/ShoppingCartTable.tsx
Labels: frontend 👼

#119 Changing order schema
  restapi/carts/Cart.ts
  restapi/carts/CartController.ts
  restapi/carts/CartRoutes.ts
  restapi/orders/Order.ts
  restapi/products/Product.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Checkout.tsx
  webapp/src/components/OrderDetails.tsx
  webapp/src/components/OrderList.tsx
  webapp/src/components/Review.tsx
  webapp/src/helpers/ShoppingCartHelper.ts
  webapp/src/shared/shareddtypes.ts
Labels: database 📦, application logic 📐, backend 🐱‍👤, delivery contribution ✉️

#121 Authenticated requests
  restapi/carts/Cart.ts
  restapi/carts/CartController.ts
  restapi/carts/CartRoutes.ts
  restapi/orders/OrderController.ts
  restapi/orders/OrderProduct.ts
  restapi/orders/OrderRoutes.ts
  restapi/products/ProductController.ts
  restapi/products/ProductRoutes.ts
  restapi/reviews/ReviewController.ts
  restapi/reviews/ReviewRoutes.ts
  restapi/server.ts
  restapi/users/UserController.ts
  restapi/users/UserRoutes.ts
  restapi/utils/generateToken.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Checkout.tsx
  webapp/src/components/OrderDetails.tsx
  webapp/src/components/OrderList.tsx
  webapp/src/components/Shop.tsx
Labels: bug 🐛, database 📦, backend 🐱‍👤

#120 Improving the general looks of the page and WebId usage
  restapi/users/User.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Billing.tsx
  webapp/src/components/Checkout.tsx
  webapp/src/components/FeaturedProducts.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/OrderList.tsx
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductDetails.tsx
  webapp/src/components/ProductList.tsx
  webapp/src/components/ReviewDialog.tsx
  webapp/src/components/ShippingCosts.tsx
  webapp/src/components/Shopping.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/components/ShoppingCartTable.tsx
  webapp/src/components/SignUp.tsx
  webapp/src/components/StockAlert.tsx
  webapp/src/components/WebIdRadioGroup.tsx
  webapp/src/helpers/ReviewHelper.ts
  webapp/src/helpers/ShoppingCartHelper.ts
  webapp/src/helpers/SolidHelper.ts
  webapp/src/images/not-found.png
  webapp/src/shared/shareddtypes.ts
Labels: bug 🐛, database 📦, application logic 📐, frontend 👼, i made something 😇

#123 Improving the way we show the product items
  webapp/src/components/ProductBox.tsx
  webapp/src/components/ProductList.tsx
Labels: frontend 👼, i made something 😇

#127 Store images on db
  restapi/package-lock.json
  restapi/package.json
  restapi/products/Product.ts
  restapi/products/ProductController.ts
  restapi/products/ProductRoutes.ts
  restapi/server.ts
  restapi/utils/multer.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/FeaturedProducts.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Shop.tsx
  webapp/src/components/cart/Billing.tsx
  webapp/src/components/cart/Checkout.tsx
  webapp/src/components/cart/ShippingCosts.tsx
  webapp/src/components/cart/ShoppingCart.tsx
  webapp/src/components/cart/ShoppingCartTable.tsx
  webapp/src/components/orders/OrderDetails.tsx
  webapp/src/components/orders/OrderList.tsx
  webapp/src/components/products/ProductBox.tsx
  webapp/src/components/products/ProductComment.tsx
  webapp/src/components/products/ProductCommentList.tsx
  webapp/src/components/products/ProductDetails.tsx
  webapp/src/components/products/ProductList.tsx
  webapp/src/components/products/ProductSpeedDial.tsx
  webapp/src/components/products/Review.tsx
  webapp/src/components/products/ReviewDialog.tsx
  webapp/src/components/products/ShareDialog.tsx
  webapp/src/components/products/UploadProduct.tsx
  webapp/src/components/register/SignIn.tsx
  webapp/src/components/register/SignUp.tsx
  webapp/src/helpers/CheckFieldsHelper.ts
  webapp/src/helpers/ImageHelper.ts
  webapp/src/images/1000.png
  webapp/src/images/1001.png
  webapp/src/images/1002.png
  webapp/src/images/1003.png
  webapp/src/shared/shareddtypes.ts
Labels: database 📦, application logic 📐, backend 🐱‍👤, frontend 👼

#130 Fixing orders views
  webapp/src/components/cart/Checkout.tsx
  webapp/src/components/cart/Review.tsx
  webapp/src/components/orders/OrderDetails.tsx
  webapp/src/components/orders/OrderList.tsx
  webapp/src/components/orders/StatusMessage.tsx
  webapp/src/shared/shareddtypes.ts
Labels: application logic 📐, frontend 👼

#138 Products pagination
  webapp/src/components/Home.tsx
  webapp/src/components/Shop.tsx
Labels: frontend 👼

#140 Orders filter
  webapp/src/components/orders/OrderList.tsx
Labels: frontend 👼

#136 Controlling access to routes attending to roles
  restapi/products/ProductController.ts
  webapp/src/App.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/ShowByRoles.tsx
  webapp/src/components/cart/Checkout.tsx
  webapp/src/components/orders/OrderDetails.tsx
  webapp/src/components/orders/OrderList.tsx
  webapp/src/components/products/DeleteProduct.tsx
  webapp/src/components/products/UploadProduct.tsx
  webapp/src/components/register/SignIn.tsx
  webapp/src/components/register/SignUp.tsx
  webapp/src/images/1.png
Labels: application logic 📐, frontend 👼

#157 Angel bug fixing branch
  webapp/Dockerfile
  webapp/src/App.tsx
  webapp/src/components/cart/Billing.tsx
  webapp/src/components/checkout/Billing.tsx
  webapp/src/components/checkout/Checkout.tsx
  webapp/src/components/checkout/OrderConfirmation.tsx
  webapp/src/components/checkout/Review.tsx
  webapp/src/components/checkout/ShippingCosts.tsx
  webapp/src/components/dashboard/DashboardContent.tsx
  webapp/src/components/dashboard/orders/OrderDetails.tsx
  webapp/src/components/dashboard/orders/OrderList.tsx
  webapp/src/components/dashboard/products/ProductList.tsx
  webapp/src/components/dashboard/products/UploadProduct.tsx
  webapp/src/components/register/SignIn.tsx
  webapp/src/components/register/SignUp.tsx
  webapp/src/helpers/SolidHelper.ts
  webapp/src/shared/shareddtypes.ts
Labels: bug 🐛, frontend 👼

#156 Update stock moved to the restapi
  restapi/orders/OrderController.ts
  restapi/products/ProductController.ts
  webapp/src/components/checkout/Checkout.tsx
Labels: application logic 📐, backend 🐱‍👤

#159 Including some charts that work just fine
  restapi/orders/OrderController.ts
  restapi/orders/OrderRoutes.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/NavBar.tsx
  webapp/src/components/dashboard/Chart.tsx
  webapp/src/components/dashboard/DashboardContent.tsx
  webapp/src/components/dashboard/DashboardSideBar.tsx
  webapp/src/components/dashboard/charts/LastMonthOrdersChart.tsx
  webapp/src/components/dashboard/charts/TotalOrdersChart.tsx
  webapp/src/components/dashboard/charts/TotalReceivedOrdersChart.tsx
  webapp/src/components/dashboard/charts/UniqueBuyersChart.tsx
  webapp/src/components/dashboard/products/DeleteProduct.tsx
  webapp/src/components/dashboard/products/ProductList.tsx
  webapp/src/components/dashboard/products/UploadProduct.tsx
  webapp/src/components/dashboard/utils/Subtitle.tsx
  webapp/src/components/dashboard/utils/Title.tsx
  webapp/src/components/navigation/Drawer.tsx
  webapp/src/components/navigation/NavBar.tsx
  webapp/src/components/navigation/NavMenu.tsx
  webapp/src/components/navigation/UserMenuButton.tsx
  webapp/src/helpers/RoleHelper.ts
Labels: application logic 📐, i made something 😇

#161 Front end initial tests
  webapp/src/App.test.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/tests/ProductBox.test.tsx
  webapp/src/tests/ProductList.test.tsx
  webapp/src/tests/StockAlert.test.tsx
Labels: frontend 👼

#200 Merging the work we have until this point
  .gitignore
  restapi/orders/OrderController.ts
  restapi/orders/OrderRoutes.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/users/UserController.ts
  webapp/README.md
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/NavBar.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/components/dashboard/Chart.tsx
  webapp/src/components/dashboard/DashboardContent.tsx
  webapp/src/components/dashboard/DashboardSideBar.tsx
  webapp/src/components/dashboard/charts/LastMonthOrdersChart.tsx
  webapp/src/components/dashboard/charts/TotalOrdersChart.tsx
  webapp/src/components/dashboard/charts/TotalReceivedOrdersChart.tsx
  webapp/src/components/dashboard/charts/UniqueBuyersChart.tsx
  webapp/src/components/dashboard/products/DeleteProduct.tsx
  webapp/src/components/dashboard/products/ProductList.tsx
  webapp/src/components/dashboard/products/UploadProduct.tsx
  webapp/src/components/dashboard/utils/Subtitle.tsx
  webapp/src/components/dashboard/utils/Title.tsx
  webapp/src/components/navigation/Drawer.tsx
  webapp/src/components/navigation/NavBar.tsx
  webapp/src/components/navigation/NavMenu.tsx
  webapp/src/components/navigation/UserMenuButton.tsx
  webapp/src/helpers/RoleHelper.ts
  webapp/src/tests/Example.test.tsx
  webapp/src/tests/StockAlert.test.tsx
  webapp/src/tests/cart/Example.test.tsx
  webapp/src/tests/checkout/Example.test.tsx
  webapp/src/tests/dashboard/orders/Example.test.tsx
  webapp/src/tests/dashboard/products/Example.test.tsx
  webapp/src/tests/dialogs/Example.test.tsx
  webapp/src/tests/products/ProductBox.test.tsx
  webapp/src/tests/products/ProductList.test.tsx
  webapp/src/tests/register/Example.test.tsx
Labels: other ⚙

#199 Minor bug fixing of Tables and Logout
  webapp/src/api/api.ts
  webapp/src/components/dashboard/orders/OrderList.tsx
  webapp/src/components/dashboard/products/ProductList.tsx
  webapp/src/components/navigation/NavBar.tsx
  webapp/src/components/navigation/NavMenu.tsx
  webapp/src/components/navigation/UserMenuButton.tsx
  webapp/src/helpers/RoleHelper.ts
Labels: application logic 📐, frontend 👼

#202 Using a test database for testing the rest api
  restapi/orders/OrderController.ts
  restapi/products/ProductController.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/users/UserController.ts
  restapi/utils/generateToken.ts
  webapp/src/api/api.ts
Labels: database 📦, backend 🐱‍👤, test 🔧

#204 Shopping cart tests
  webapp/src/tests/cart/ShoppingCart.test.tsx
  webapp/src/tests/cart/ShoppingCartTable.test.tsx
Labels: frontend 👼, test 🔧

#205 Product details, comments and list tests
  webapp/src/components/products/ProductComment.tsx
  webapp/src/components/products/ProductDetails.tsx
  webapp/src/tests/products/ProductComment.test.tsx
  webapp/src/tests/products/ProductCommentList.test.tsx
  webapp/src/tests/products/ProductDetails.test.tsx
Labels: frontend 👼, test 🔧
